# Generated by Django 5.2.6 on 2025-09-16 06:24

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomerUserManager()),
            ],
        ),
    ]
