# Generated by Django 5.2.6 on 2025-09-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_email_sent_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_email_sent',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
