# Generated by Django 5.2.6 on 2025-09-17 06:14

import django.core.validators
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(default=polls.models.one_week_from_now, validators=[django.core.validators.MinValueValidator(polls.models.one_hour_from_now)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=polls.models.current_time, validators=[django.core.validators.MinValueValidator(polls.models.current_time)]),
        ),
    ]
