# Generated by Django 5.2.6 on 2025-09-14 07:43

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 14, 8, 43, 26, 344893, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 14, 7, 43, 26, 344860, tzinfo=datetime.timezone.utc))]),
        ),
    ]
