# Generated by Django 5.2.6 on 2025-09-16 06:24

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_expiry_date_alter_poll_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 16, 7, 24, 57, 973563, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 16, 6, 24, 57, 973532, tzinfo=datetime.timezone.utc))]),
        ),
    ]
