# Generated by Django 5.2.6 on 2025-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_vote_options_alter_poll_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
